package com.example.siraj.model

data class NomAllah(
    val nom: String,
    val phonetique: String,
    val signification: String
)

val nomsAllah = listOf(
    NomAllah("الرَّحْمَنُ", "Ar-Rahman", "Le Tout Miséricordieux"),
    NomAllah("الرَّحِيمُ", "Ar-Rahim", "Le Très Miséricordieux"),
    NomAllah("الْمَلِكُ", "Al-Malik", "Le Souverain"),
    NomAllah("الْقُدُّوسُ", "Al-Quddus", "Le Saint"),
    NomAllah("السَّلَامُ", "As-Salam", "La Paix"),
    NomAllah("الْمُؤْمِنُ", "Al-Mu'min", "Le Rassurant"),
    NomAllah("الْمُهَيْمِنُ", "Al-Muhaymin", "Le Préservateur"),
    NomAllah("الْعَزِيزُ", "Al-Aziz", "Le Tout-Puissant"),
    NomAllah("الْجَبَّارُ", "Al-Jabbar", "Le Contraignant"),
    NomAllah("الْمُتَكَبِّرُ", "Al-Mutakabbir", "Le Superbe"),
    NomAllah("الْخَالِقُ", "Al-Khaliq", "Le Créateur"),
    NomAllah("الْبَارِئُ", "Al-Bari", "Le Producteur"),
    NomAllah("الْمُصَوِّرُ", "Al-Musawwir", "Le Formateur"),
    NomAllah("الْغَفَّارُ", "Al-Ghaffar", "Le Grand Pardonneur"),
    NomAllah("الْقَهَّارُ", "Al-Qahhar", "Le Contraignant"),
    NomAllah("الْوَهَّابُ", "Al-Wahhab", "Le Donateur gracieux"),
    NomAllah("الرَّزَّاقُ", "Ar-Razzaq", "Le Pourvoyeur"),
    NomAllah("الْفَتَّاحُ", "Al-Fattah", "Le Juge"),
    NomAllah("الْعَلِيْمُ", "Al-Alim", "L’Omniscient"),
    NomAllah("الْقَابِضُ", "Al-Qabid", "Celui qui retient"),
    NomAllah("الْبَاسِطُ", "Al-Basit", "Celui qui donne largement"),
    NomAllah("الْخَافِضُ", "Al-Khafid", "Celui qui abaisse"),
    NomAllah("الرَّافِعُ", "Ar-Rafi", "Celui qui élève"),
    NomAllah("الْمُعِزُّ", "Al-Mu'izz", "Celui qui honore"),
    NomAllah("المُذِلُّ", "Al-Mudhill", "Celui qui humilie"),
    NomAllah("السَّمِيعُ", "As-Sami", "L’Audient"),
    NomAllah("الْبَصِيرُ", "Al-Basir", "Le Clairvoyant"),
    NomAllah("الْحَكَمُ", "Al-Hakam", "Le Juge"),
    NomAllah("الْعَدْلُ", "Al-Adl", "Le Juste"),
    NomAllah("اللَّطِيفُ", "Al-Latif", "Le Subtil, Bienveillant"),
    NomAllah("الْخَبِيرُ", "Al-Khabir", "Le Bien-Informé"),
    NomAllah("الْحَلِيمُ", "Al-Halim", "Le Très Clément"),
    NomAllah("الْعَظِيمُ", "Al-Azim", "L’Immense"),
    NomAllah("الْغَفُورُ", "Al-Ghafur", "Le Tout Pardonneur"),
    NomAllah("الشَّكُورُ", "Ash-Shakur", "Le Très Reconnaissant"),
    NomAllah("الْعَلِيُّ", "Al-Aliyy", "Le Très Haut"),
    NomAllah("الْكَبِيرُ", "Al-Kabir", "Le Très Grand"),
    NomAllah("الْحَفِيظُ", "Al-Hafiz", "Le Préservateur"),
    NomAllah("المُقيِت", "Al-Muqit", "Le Nourricier"),
    NomAllah("الْحسِيبُ", "Al-Hasib", "Le Suffisant"),
    NomAllah("الْجَلِيلُ", "Al-Jalil", "Le Majestueux"),
    NomAllah("الْكَرِيمُ", "Al-Karim", "Le Très Généreux"),
    NomAllah("الرَّقِيبُ", "Ar-Raqib", "L’Observateur"),
    NomAllah("الْمُجِيبُ", "Al-Mujib", "Celui qui exauce"),
    NomAllah("الْوَاسِعُ", "Al-Wasi", "L’Immense"),
    NomAllah("الْحَكِيمُ", "Al-Hakim", "Le Sage"),
    NomAllah("الْوَدُودُ", "Al-Wadud", "Le Très Affectueux"),
    NomAllah("الْمَجِيدُ", "Al-Majid", "Le Très Glorieux"),
    NomAllah("الْبَاعِثُ", "Al-Ba'ith", "Le Ressusciteur"),
    NomAllah("الشَّهِيدُ", "Ash-Shahid", "Le Témoin"),
    NomAllah("الْحَقُ", "Al-Haqq", "La Vérité"),
    NomAllah("الْوَكِيلُ", "Al-Wakil", "Le Garant"),
    NomAllah("الْقَوِيُ", "Al-Qawiyy", "Le Très Fort"),
    NomAllah("الْمَتِينُ", "Al-Matin", "Le Très Ferme"),
    NomAllah("الْوَلِيُّ", "Al-Wali", "Le Protecteur"),
    NomAllah("الْحَمِيدُ", "Al-Hamid", "Le Digne de louange"),
    NomAllah("الْمُحْصِي", "Al-Muhsi", "Celui qui dénombre tout"),
    NomAllah("الْمُبْدِئُ", "Al-Mubdi", "Le Créateur initial"),
    NomAllah("الْمُعِيدُ", "Al-Mu'id", "Celui qui redonne vie"),
    NomAllah("الْمُحْيِي", "Al-Muhyi", "Celui qui donne la vie"),
    NomAllah("اَلْمُمِيتُ", "Al-Mumit", "Celui qui fait mourir"),
    NomAllah("الْحَيُّ", "Al-Hayy", "Le Vivant"),
    NomAllah("الْقَيُّومُ", "Al-Qayyum", "L’Immuable"),
    NomAllah("الْوَاجِدُ", "Al-Wajid", "Le Glorieux"),
    NomAllah("الْمَاجِدُ", "Al-Majid", "Le Noble"),
    NomAllah("الواحِدُ", "Al-Wahid", "L’Unique"),
    NomAllah("اَلاَحَدُ", "Al-Ahad", "L’Un"),
    NomAllah("الصَّمَدُ", "As-Samad", "L’Absolu"),
    NomAllah("الْقَادِرُ", "Al-Qadir", "Le Tout-Puissant"),
    NomAllah("الْمُقْتَدِرُ", "Al-Muqtadir", "Le Très Capable"),
    NomAllah("الْمُقَدِّمُ", "Al-Muqaddim", "Celui qui fait avancer"),
    NomAllah("الْمُؤَخِّرُ", "Al-Mu'akhkhir", "Celui qui fait reculer"),
    NomAllah("الأوَّلُ", "Al-Awwal", "Le Premier"),
    NomAllah("الآخِرُ", "Al-Akhir", "Le Dernier"),
    NomAllah("الظَّاهِرُ", "Az-Zahir", "L’Apparent"),
    NomAllah("الْبَاطِنُ", "Al-Batin", "Le Caché"),
    NomAllah("الْوَالِي", "Al-Waliyy", "Le Gouverneur"),
    NomAllah("الْمُتَعَالِي", "Al-Muta'ali", "L’Exalté"),
    NomAllah("الْبَرُّ", "Al-Barr", "Le Bienfaiteur"),
    NomAllah("التَّوَابُ", "At-Tawwab", "Celui qui accepte le repentir"),
    NomAllah("الْمُنْتَقِمُ", "Al-Muntaqim", "Le Vengeur"),
    NomAllah("العَفُوُ", "Al-Afuww", "Le Pardonneur"),
    NomAllah("الرَّؤُوفُ", "Ar-Ra'uf", "Le Très Clément"),
    NomAllah("مَالِكُ الْمُلْكِ", "Malik al-Mulk", "Le Maître du Royaume"),
    NomAllah("ذُوالْجَلاَلِ وَالإكْرَامِ", "Dhu al-Jalali wal-Ikram", "Le Détenteur de la Majesté"),
    NomAllah("الْمُقْسِطُ", "Al-Muqsit", "L’Équitable"),
    NomAllah("الْجَامِعُ", "Al-Jami", "Le Rassembleur"),
    NomAllah("الْغَنيُّ", "Al-Ghaniyy", "Le Suffisant à soi-même"),
    NomAllah("الْمُغْنِيُ", "Al-Mughni", "L’Enrichisseur"),
    NomAllah("اَلْمَانِعُ", "Al-Mani", "Le Protecteur"),
    NomAllah("الضَّارَ", "Ad-Darr", "Celui qui afflige"),
    NomAllah("النَّافِعُ", "An-Nafi", "Le Bienfaiteur"),
    NomAllah("النُّورُ", "An-Nur", "La Lumière"),
    NomAllah("الْهَادِي", "Al-Hadi", "Le Guide"),
    NomAllah("الْبَدِيعُ", "Al-Badi", "L’Incomparable"),
    NomAllah("اَلْبَاقِي", "Al-Baqi", "Le Permanent"),
    NomAllah("الْوَارِثُ", "Al-Warith", "L’Héritier"),
    NomAllah("الرَّشِيدُ", "Ar-Rashid", "Le Guide Infaillible"),
    NomAllah("الصَّبُورُ", "As-Sabur", "Le Très Patient")
)
